In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [19]:
arr = np.array([1,2,3,7,4,5])
print(arr)

[1 2 3 7 4 5]


In [7]:
print(np.mean(arr))

3.6666666666666665


In [8]:
print(np.median(arr))

3.5


# 0-D Array

In [16]:
arr_0D = np.array(32)
print(arr_0D)

32


# 1-D Array

In [17]:
arr_1D = np.array([1,3,5,7,9,11])
print(arr_1D)

[ 1  3  5  7  9 11]


# 2-D Array

In [14]:
arr_2D = np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(arr_2D)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


# 3-D Array

In [13]:
arr_3D = np.array([[[1,3,5,7,9],[2,4,6,8,10]],[[2,4,6,8,10],[1,3,5,7,9]]])
print(arr_3D)

[[[ 1  3  5  7  9]
  [ 2  4  6  8 10]]

 [[ 2  4  6  8 10]
  [ 1  3  5  7  9]]]


# No. of Dimentions of Array

In [18]:
print(arr.ndim)
print(arr_0D.ndim)
print(arr_1D.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

1
0
1
2
3


# Reshaping of Array

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr.reshape(5,2)
print(arr1)
arr1.shape

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


(5, 2)

# Flattening the Array

In [10]:
arr2 = arr.reshape(-1)
print(arr2)
arr2.shape

[ 1  2  3  4  5  6  7  8  9 10]


(10,)

# Indexing in Array

In [12]:
X = np.array([1,2,3,4,5])
print(X[0])

1


In [13]:
print(X[2] + X[4])

8


# Array-Iterating

In [7]:
Y = np.array([[1,3,5],[2,4,6]])

for x in Y:
    for y in x:
        print(y)

1
3
5
2
4
6


# Slicing Arrays

In [12]:
Z = np.array([1,3,5,7,9,11,13])
print(Z[:4:2])

[1 5]


In [15]:
print(arr_2D[1,1:])

[ 4  6  8 10]


# Searching Array

In [20]:
A = np.where(arr == 3)

print(A)

(array([2], dtype=int64),)


In [23]:
B = np.where(arr%2 ==0)
print(B)

(array([1, 4], dtype=int64),)


# Sorting

In [25]:
C = np.array(['Banana','Apple','Mango',1,3,2])
print(np.sort(C))

['1' '2' '3' 'Apple' 'Banana' 'Mango']
